# Generated by Django 6.0.7 on 2026-08-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deardiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
